import { Region, Place, Transport, WaitingSpot } from './types';

export const REGIONS: Region[] = [
  {
    id: "buyeo",
    name: "부여",
    province: "충남",
    shortDescription: "백제 역사와 백마강, 궁남지가 이어지는 역사·문화 여행지",
    vibeTitle: "백제 감성 따라 걷는 하루",
    heroImage: "from-amber-400 via-amber-500 to-amber-600",
    characterName: "부리",
    characterEmoji: "👑",
    characterImage: "",
    characterCatchphrase: "부여는 천천히 걸을수록 매력이 보여요. 제가 길 잃지 않게 같이 안내할게요.",
    characterDescriptionShort: "백제 왕관을 머리에 쓴 따뜻하고 사랑스러운 아기새",
    characterDescription: "부여의 백제 왕관을 머리에 쓴 아기새 캐릭터입니다. 작은 여행 가방을 메고 부여의 구석구석을 사랑스럽게 가이드합니다.",
    themes: ["역사", "문화", "사진", "수상관광"],
    hashtags: ["백제", "궁남지", "백마강"],
    isMvpAvailable: true,
    imageStyle: "from-amber-50 to-amber-100",
    colorTheme: "gold",
    characterImageStyle: "백제 금동관 모양 모자를 쓴 말랑한 아기 새 인형",
    characterToyDescription: "작은 지도 주머니와 금빛 왕관 장식을 맨 부여 여행 수호 인형",
    characterTone: "따뜻하고 신뢰감 있는 여행 친구",
    regionVisualKeyword: "백제, 궁남지 연꽃, 백마강 황포돛배, 금빛 역사",
    regionIcon: "👑",
    regionHashtags: ["#백제", "#궁남지", "#백마강"]
  },
  {
    id: "gongju",
    name: "공주",
    province: "충남",
    shortDescription: "무령왕릉과 산성, 금강이 어우러진 교육·역사 거점 시",
    vibeTitle: "무령왕의 숨결을 느끼는 하루",
    heroImage: "from-blue-400 via-blue-500 to-blue-600",
    characterName: "곰이",
    characterEmoji: "🏯",
    characterImage: "",
    characterCatchphrase: "공산성 성곽길을 따라 걸으며, 한옥의 고즈넉함을 느껴보세요.",
    characterDescriptionShort: "공산성 밤송이 모자를 쓴 아기곰 수호신",
    characterDescription: "공산성 돌담과 무령왕릉의 비밀을 사랑하는, 볼이 발그레하고 귀여운 아기곰 수호신입니다.",
    themes: ["역사", "문화", "가족", "공예"],
    hashtags: ["역사", "공산성", "한옥감성"],
    isMvpAvailable: false,
    imageStyle: "from-blue-50 to-blue-100",
    colorTheme: "blue",
    characterImageStyle: "공산성 모양 밤송이 모자를 쓴 동글동글한 봉제 곰 인형",
    characterToyDescription: "나무 나침반 백팩을 멘 앙증맞은 공주 안내 친구",
    characterTone: "다정하고 차분한 동네 지킴이",
    regionVisualKeyword: "공산성 돌담, 무령왕릉 고분, 한옥마을, 도보산책",
    regionIcon: "🏯",
    regionHashtags: ["#역사", "#공산성", "#한옥감성"]
  },
  {
    id: "seocheon",
    name: "서천",
    province: "충남",
    shortDescription: "갈대밭과 갯벌, 국립생태원이 있는 생태·힐링 여행지",
    vibeTitle: "푸른 갈대밭과 바다가 속삭이는 길",
    heroImage: "from-green-400 via-green-500 to-green-600",
    characterName: "서치",
    characterEmoji: "🌾",
    characterImage: "",
    characterCatchphrase: "은빛 갈대 흔들리는 소리를 들으며 몸과 마음에 쉼표를 찍어볼까요.",
    characterDescriptionShort: "서천 갈대잎 귀를 쫑긋거리는 바람 요정 아기여우",
    characterDescription: "신성리 갈대밭의 바람 소리를 들으며 소나무 숲과 갯벌을 씩씩하게 뛰노는 바람 요정 아기여우입니다.",
    themes: ["자연", "생태", "먹거리", "바다"],
    hashtags: ["갈대밭", "바다", "생태"],
    isMvpAvailable: false,
    imageStyle: "from-green-50 to-green-100",
    colorTheme: "green",
    characterImageStyle: "갈대 잎모양 귀와 푹신한 꼬리가 달린 말랑한 아기여우 인형",
    characterToyDescription: "작은 돋보기 주머니를 들고 갯벌을 뛰노는 힐링 요정 인형",
    characterTone: "자연스럽고 편안한 생태 쉼터 가이드",
    regionVisualKeyword: "신성리 갈대밭, 서해 갯벌, 국립생태원 온실, 노을숲길",
    regionIcon: "🌾",
    regionHashtags: ["#갈대밭", "#바다", "#생태"]
  },
  {
    id: "yesan",
    name: "예산",
    province: "충남",
    shortDescription: "예당호 출렁다리와 전통 사과, 백종원 시장이 뜨거운 미식 도시",
    vibeTitle: "백종원 미식 탐방과 힐링 호수",
    heroImage: "from-red-400 via-red-500 to-red-600",
    characterName: "예삐",
    characterEmoji: "🍎",
    characterImage: "",
    characterCatchphrase: "든든하고 맛있는 전통 시장 투어부터 예당호 출렁다리 도보까지 안내해 드릴게요.",
    characterDescriptionShort: "머리에 사과핀을 꽂은 예산 시장의 작은 아기 셰프람쥐",
    characterDescription: "예산 사과와 출렁다리를 자랑하며, 예산 시장의 전통 먹거리를 누구보다 알차게 가이드하는 먹방 셰프람쥐입니다.",
    themes: ["먹거리", "온천", "자연", "레저"],
    hashtags: ["시장", "먹거리", "레트로"],
    isMvpAvailable: false,
    imageStyle: "from-red-50 to-red-100",
    colorTheme: "red",
    characterImageStyle: "머리에 예산 빨간 사과핀을 꽂은 복슬복슬한 다람쥐 인형",
    characterToyDescription: "작은 보따리와 꼬마 스푼을 메고 있는 전통시장 미식 인형",
    characterTone: "활기차고 든든한 로컬 미식 가이드",
    regionVisualKeyword: "백종원 예산시장, 예당호 출렁다리, 황토사과밭, 온천천",
    regionIcon: `🍎`,
    regionHashtags: ["#시장", "#먹거리", "#레트로"]
  },
  {
    id: "cheongyang",
    name: "청양",
    province: "충남",
    shortDescription: "칠갑산의 울창한 숲과 알프스마을이 있는 청정 산악 지대",
    vibeTitle: "칠갑산 청정 숲과 짜릿한 출렁다리",
    heroImage: "from-rose-400 via-rose-500 to-rose-600",
    characterName: "고추리",
    characterEmoji: "🌶️",
    characterImage: "",
    characterCatchphrase: "칠갑산 청정 공기를 마시며 출렁다리 너머 자연 속으로 모험을 떠나볼까요.",
    characterDescriptionShort: "머리에 빨간 고추 모자를 쓴 청양의 열정 꼬마 요정",
    characterDescription: "청양 고추의 매콤함을 닮아 에너지가 넘치고 칠갑산을 기가 막히게 잘 타는 등산 가이드 요정입니다.",
    themes: ["자연", "체험", "겨울", "가족"],
    hashtags: ["칠갑산", "출렁다리", "자연"],
    isMvpAvailable: false,
    imageStyle: "from-rose-50 to-rose-100",
    colorTheme: "rose",
    characterImageStyle: "빨간 고추 모자를 푹 눌러쓴 말랑통통한 고추 요정 인형",
    characterToyDescription: "자그마한 산악인 지팡이와 보도 로드 맵을 쥔 모험 인형",
    characterTone: "열정적이고 건강한 숲속 힐링 메이트",
    regionVisualKeyword: "칠갑산 등산로, 천장호 출렁다리, 알프스마을 빙벽, 청정계곡",
    regionIcon: "🌶️",
    regionHashtags: ["#칠갑산", "#출렁다리", "#자연"]
  },
  {
    id: "boryeong",
    name: "보령",
    province: "충남",
    shortDescription: "대천해수욕장과 세계적인 머드 축제, 서해안 레저의 메카",
    vibeTitle: "서해 머드와 파도가 춤추는 레저",
    heroImage: "from-cyan-400 via-cyan-500 to-cyan-600",
    characterName: "머디",
    characterEmoji: "🦀",
    characterImage: "",
    characterCatchphrase: "대천해수욕장의 시원한 모래사장에서 신나는 레포츠와 머드 놀이를 함께해요.",
    characterDescriptionShort: "머드 갯벌에서 태어난 물놀이 대장 꼬마 크랩",
    characterDescription: "대천해수욕장의 고운 모래와 신나는 머드 갯벌 체험을 동네 앞마당처럼 꿰고 있는 크랩 요정입니다.",
    themes: ["바다", "레저", "축제", "체험"],
    hashtags: ["머드축제", "바다", "액티비티"],
    isMvpAvailable: false,
    imageStyle: "from-cyan-50 to-cyan-100",
    colorTheme: "cyan",
    characterImageStyle: "눈알이 뱅글뱅글 돌아가는 둥근 꽃게 모양 봉제 인형",
    characterToyDescription: "머드 주머니와 꼬마 서핑보드를 메고 물장구를 치는 크랩 인형",
    characterTone: "에너지 넘치고 활발한 액티비티 파트너",
    regionVisualKeyword: "대천 머드광장, 짚트랙 레저, 서해안 은빛 모래, 노을캠핑",
    regionIcon: "🦀",
    regionHashtags: ["#머드축제", "#바다", "#액티비티"]
  },
  {
    id: "taean",
    name: "태안",
    province: "충남",
    shortDescription: "끝없는 해안선과 안면도 소나무 숲, 일몰이 아름다운 바다정원",
    vibeTitle: "안면도 솔향과 붉은 노을길",
    heroImage: "from-teal-400 via-teal-500 to-teal-600",
    characterName: "태리",
    characterEmoji: "🐚",
    characterImage: "",
    characterCatchphrase: "붉은 노을이 가득한 안면도 솔밭과 꽃지 해변 산책길을 보여드릴게요.",
    characterDescriptionShort: "진주조개 배낭을 멘 아기 소라요정",
    characterDescription: "꽃지해수욕장의 환상적인 낙조 풍경을 귀여운 조개 등껍질에 품고 다니는 노을 요정입니다.",
    themes: ["바다", "자연", "사진", "힐링"],
    hashtags: ["노을", "바다", "해변"],
    isMvpAvailable: false,
    imageStyle: "from-teal-50 to-teal-100",
    colorTheme: "teal",
    characterImageStyle: "등껍질 속에 쏙 숨을 수 있는 부드러운 소라 요정 인형",
    characterToyDescription: "진주조개 배낭을 메고 귓가에 파도 소리를 들려주는 감성 인형",
    characterTone: "감성적이고 고요한 사색의 힐링 친구",
    regionVisualKeyword: "꽃지 낙조, 안면도 소나무길, 삼봉 갯벌, 파도 산책",
    regionIcon: "🐚",
    regionHashtags: ["#노을", "#바다", "#해변"]
  },
  {
    id: "nonsan",
    name: "논산",
    province: "충남",
    shortDescription: "선샤인랜드와 탑정호 출렁다리, 훈련소와 딸기의 고장",
    vibeTitle: "논산 딸기와 추억의 사극 촬영장",
    heroImage: "from-pink-400 via-pink-500 to-pink-600",
    characterName: "베리",
    characterEmoji: "🍓",
    characterImage: "",
    characterCatchphrase: "달콤한 딸기 향 가득한 탑정호변과 추억 서린 드라마 세트장을 걸어봐요.",
    characterDescriptionShort: "논산 딸기밭의 달콤함을 머금은 아기 요정",
    characterDescription: "논산 딸기의 싱그러움을 간직한 채 선샤인랜드 사극 촬영장 지름길을 알려주는 가이드입니다.",
    themes: ["체험", "역사", "자연", "군문화"],
    hashtags: ["선샤인랜드", "딸기", "출렁다리"],
    isMvpAvailable: false,
    imageStyle: "from-pink-50 to-pink-100",
    colorTheme: "pink",
    characterImageStyle: "빨간 딸기 모양 얼굴에 초록색 잎사귀 스카프를 한 딸기 인형",
    characterToyDescription: "동그랗고 폭신폭신하며 한 손에 작은 드라마 슬레이트를 든 아기 요정",
    characterTone: "상큼하고 정보력 넘치는 근교 여행 가이드",
    regionVisualKeyword: "선샤인랜드 세트장, 탑정호 출렁다리, 딸기체험, 낭만산책",
    regionIcon: "🍓",
    regionHashtags: ["#선샤인랜드", "#딸기", "#출렁다리"]
  },
  {
    id: "geumsan",
    name: "금산",
    province: "충남",
    shortDescription: "인삼의 고장이자 적벽강 청정 자연을 품은 웰니스 특화 지역",
    vibeTitle: "인삼 향 가득한 건강 치유 여행",
    heroImage: "from-emerald-400 via-emerald-500 to-emerald-600",
    characterName: "사미",
    characterEmoji: "🌱",
    characterImage: "",
    characterCatchphrase: "바쁜 일상에서 벗어나, 푸른 적벽강과 약초 숲에서 웰니스 힐링을 맛보세요.",
    characterDescriptionShort: "인삼 줄기 머리핀을 꽂은 웰니스 아기 산삼",
    characterDescription: "적벽강 강바람을 맞고 자라 피로회복 편백숲길과 영양 가득 인삼 먹거리를 알려주는 치유 요정입니다.",
    themes: ["힐링", "체험", "건강", "자연"],
    hashtags: ["인삼", "적벽강", "웰니스"],
    isMvpAvailable: false,
    imageStyle: "from-emerald-50 to-emerald-100",
    colorTheme: "emerald",
    characterImageStyle: "인삼 줄기 모양 안테나가 달린 말랑한 산삼 요정 인형",
    characterToyDescription: "뜨끈한 약초 파우치를 들고 웰니스 숲길을 치유하는 건강 인형",
    characterTone: "따스하고 온화한 건강 치유 지킴이",
    regionVisualKeyword: "적벽강 강변길, 약초시장, 숲속 치유 온천, 삼림욕림",
    regionIcon: "🌱",
    regionHashtags: ["#인삼", "#적벽강", "#웰니스"]
  },
  {
    id: "cheonan",
    name: "천안",
    province: "충남",
    shortDescription: "독립기념관과 호두과자, 충청남도 교통과 교육의 중심 도시",
    vibeTitle: "독립 기개 서린 교통 요충지 여행",
    heroImage: "from-orange-400 via-orange-500 to-orange-600",
    characterName: "넛이",
    characterEmoji: "🌰",
    characterImage: "",
    characterCatchphrase: "교통 요충지 천안의 뚜벅이 이동 경로와 독립기념관의 역사 동선을 쉽게 짚어드릴게요.",
    characterDescriptionShort: "천안 삼거리 호두나무 출신의 아기람쥐 대장",
    characterDescription: "천안의 맛있는 호두과자와 환승하기 좋은 뚜벅이 이동 경로를 속속들이 알고 있는 똘똘한 대장입니다.",
    themes: ["역사", "실내", "쇼핑", "도시관광"],
    hashtags: ["독립기념관", "호두과자", "삼거리"],
    isMvpAvailable: false,
    imageStyle: "from-orange-50 to-orange-100",
    colorTheme: "orange",
    characterImageStyle: "고소한 호두 껍데기 모자를 쓴 통통한 다람쥐 봉제 인형",
    characterToyDescription: "배낭에 진짜 호두과자 모형을 넣고 지하철과 버스 길을 안내하는 아기 인형",
    characterTone: "듬직하고 쾌활한 철도/버스 지름길 길잡이",
    regionVisualKeyword: "독립기념관 야외광장, 호두과자 골목, 천안삼거리 공원, 상설쇼핑몰",
    regionIcon: "🌰",
    regionHashtags: ["#독립기념관", "#호두과자", "#삼거리"]
  },
  {
    id: "asan",
    name: "아산",
    province: "충남",
    shortDescription: "현충사와 지중해마을, 오래된 온천 유적이 살아 숨 쉬는 힐링지",
    vibeTitle: "스파와 영웅의 얼이 숨 쉬는 온천지",
    heroImage: "from-indigo-400 via-indigo-500 to-indigo-600",
    characterName: "스파키",
    characterEmoji: "♨️",
    characterImage: "",
    characterCatchphrase: "현충사의 경건함을 마음에 담고, 지중해마을 골목길에서 사진을 남겨볼까요.",
    characterDescriptionShort: "온천수 물방울 머리를 한 온천 요정",
    characterDescription: "아산 온천수의 기운을 듬뿍 받아 에너지가 넘치며 충무공 이순신 장군의 현충사도 위풍당당하게 소개합니다.",
    themes: ["온천", "역사", "문화", "힐링"],
    hashtags: ["온천", "현충사", "지중해마을"],
    isMvpAvailable: false,
    imageStyle: "from-indigo-50 to-indigo-100",
    colorTheme: "indigo",
    characterImageStyle: "머리 위에 온천수 김이 피어오르는 둥글고 푸른 물방울 인형",
    characterToyDescription: "이순신 장군 장난감 목검과 스파 타월을 들고 있는 역사/온천 꼬마 수호신",
    characterTone: "식식하고 활기찬 온천/역사 안내인",
    regionVisualKeyword: "온양온천 족욕체험, 현충사 소나무길, 지중해마을 건축, 피톤치드림",
    regionIcon: "♨️",
    regionHashtags: ["#온천", "#현충사", "#지중해마을"]
  },
  {
    id: "cheongju",
    name: "청주",
    province: "충북",
    shortDescription: "직지대모와 수암골 골목, 전통과 현대 미술이 숨 쉬는 충북 거점 도시",
    vibeTitle: "역사적인 인쇄 문화와 골목 갤러리",
    heroImage: "from-slate-400 via-slate-500 to-slate-600",
    characterName: "직지",
    characterEmoji: "📜",
    characterImage: "",
    characterCatchphrase: "박물관의 지적인 조용함 and 골목 벽화마을의 미술 감성을 따라 걸어볼까요.",
    characterDescriptionShort: "한지 두루마리 리본을 맨 아기 서생쥐",
    characterDescription: "청주 고인쇄박물관과 미술관 도슨트를 맡아 세밀하게 관람 동선을 짚어주는 똑똑한 책벌레 서생쥐입니다.",
    themes: ["실내", "문화", "미술", "도시관광"],
    hashtags: ["골목미술", "수암골", "인쇄문화"],
    isMvpAvailable: false,
    imageStyle: "from-slate-50 to-slate-100",
    colorTheme: "slate",
    characterImageStyle: "한지 인쇄 족자 리본을 등에 단 지적인 책벌레 생쥐 인형",
    characterToyDescription: "둥근 뿔테안경을 쓰고 청주 현대미술 전시관을 도슨트하는 책벌레 인형",
    characterTone: "차분하고 이지적인 박물관 도슨트",
    regionVisualKeyword: "고인쇄박물관 실내, 수암골 예술골목, 시립미술관 투어, 문학산책",
    regionIcon: "📜",
    regionHashtags: ["#골목미술", "#수암골", "#인쇄문화"]
  },
  {
    id: "jecheon",
    name: "제천",
    province: "충북",
    shortDescription: "의림지와 청풍호 모노레일, 바람이 머무는 한방 웰니스 시티",
    vibeTitle: "한방 웰니스와 청풍호 수려한 비경",
    heroImage: "from-violet-400 via-violet-500 to-violet-600",
    characterName: "한비",
    characterEmoji: "🌿",
    characterImage: "",
    characterCatchphrase: "의림지의 시원한 호수림과 모노레일 비경을 구경하며 피로를 풀 시간이에요.",
    characterDescriptionShort: "제천 약초 주머니를 찬 발랄한 꼬마 다람쥐",
    characterDescription: "의림지의 시원한 강바람을 맞고 산을 잘 타며, 한방 치유 코스를 친절하게 짚어주는 아기 산악 다람쥐입니다.",
    themes: ["자연", "힐링", "레저", "수상관광"],
    hashtags: ["의림지", "모노레일", "한방웰니스"],
    isMvpAvailable: false,
    imageStyle: "from-violet-50 to-violet-100",
    colorTheme: "violet",
    characterImageStyle: "귀 뒤에 풀잎 날개가 달린 부드러운 산 다람쥐 봉제 인형",
    characterToyDescription: "목에 제천 한방 약초 주머니를 매달고 호수 바람을 가르는 안내 인형",
    characterTone: "상쾌하고 믿음직한 호수 산악 가이드",
    regionVisualKeyword: "의림지 소나무, 청풍호 모노레일, 한방 웰니스 약초원, 호반산책",
    regionIcon: "🌿",
    regionHashtags: ["#의림지", "#모노레일", "#한방웰니스"]
  },
  {
    id: "danyang",
    name: "단양",
    province: "충북",
    shortDescription: "도담삼봉과 만천하스카이워크, 패러글라이딩 모험의 천국",
    vibeTitle: "기암괴석 비경과 하늘 위 모험",
    heroImage: "from-sky-400 via-sky-500 to-sky-600",
    characterName: "단이",
    characterEmoji: "🏞️",
    characterImage: "",
    characterCatchphrase: "도담삼봉의 예스런 한 폭 그림과 짚와이어의 짜릿한 스릴을 균형 있게 경험해보세요.",
    characterDescriptionShort: "패러글라이딩 헬멧을 쓴 모험 꼬꼬마 갈매기",
    characterDescription: "단양 하늘을 날아다니며 만천하 스카이워크 절벽 코스와 시원한 동굴 탐험을 안내하는 모험 대장입니다.",
    themes: ["자연", "레저", "체험", "사진"],
    hashtags: ["도담삼봉", "패러글라이딩", "동굴"],
    isMvpAvailable: false,
    imageStyle: "from-sky-50 to-sky-100",
    colorTheme: "sky",
    characterImageStyle: "패러글라이딩 고글과 동글동글 헬멧을 착용한 갈매기 봉제 인형",
    characterToyDescription: "날개 아래 단양 관광지도를 펼쳐 든 장난기 가득한 모험가 인형",
    characterTone: "용감하고 재미있는 레저 모험 대장",
    regionVisualKeyword: "도담삼봉 강변, 만천하 스카이워크, 석회암 동굴 탐사, 패러글라이딩",
    regionIcon: "🏞️",
    regionHashtags: ["#도담삼봉", "#패러글라이딩", "#동굴"]
  },
  {
    id: "okcheon",
    name: "옥천",
    province: "충북",
    shortDescription: "정지용 문학관과 향수 100리길, 금강 줄기가 그리는 예술 마을",
    vibeTitle: "시인의 향수가 물드는 금강변 쉼터",
    heroImage: "from-fuchsia-400 via-fuchsia-500 to-fuchsia-600",
    characterName: "향수",
    characterEmoji: "🦋",
    characterImage: "",
    characterCatchphrase: "시적인 향수가 깃든 정겨운 옛 시골 기찻길과 잔잔한 금강을 함께 걸어요.",
    characterDescriptionShort: "날개 끝이 무지개 빛깔인 문학 소녀 아기 나비 요정",
    characterDescription: `정지용 시인의 감수성을 닮아 한적하고 예쁜 시골 기찻길과 금강변 억새 산책 코스를 동화처럼 속삭입니다.`,
    themes: [`역사`, `자연`, `문화`, `자전거`],
    hashtags: [`정지용문학`, `향수길`, `금강`],
    isMvpAvailable: !1,
    imageStyle: `from-fuchsia-500 to-fuchsia-700`,
    colorTheme: `fuchsia`,
    characterImageStyle: `은은한 파스텔톤 나비 날개가 달린 보들보들한 나비 아기 인형`,
    characterToyDescription: `가방에 작은 서정 시집을 꽂고 정지용 문학 생가를 거니는 문학 소녀 인형`,
    characterTone: `서정적이고 나지막한 감성 에스코트 요정`,
    regionVisualKeyword: `정지용 생가, 금강 억새길, 자전거 향수길, 시골 기찻길`,
    regionIcon: `🦋`,
    regionHashtags: [`#정지용문학`, `#향수길`, `#금강`]
  }, {
        id: `yeongdong`,
        name: `영동`,
        province: `충북`,
        shortDescription: `달콤한 국산 와인터널과 국악체험촌, 소백산 계곡이 숨겨진 고장`,
        vibeTitle: `국악 선율과 달콤한 한국 와인 여행`,
        heroImage: `from-purple-400 via-purple-500 to-purple-600`,
        characterName: `와이니`,
        characterEmoji: `🍇`,
        characterImage: ``,
        characterCatchphrase: `달콤한 와인 동굴의 이색 풍경과 가야금의 은은한 가락 속으로 초대합니다.`,
        characterDescriptionShort: `가야금 가방을 멘 포도 머리 요정`,
        characterDescription: `영동 포도 와인의 달콤함을 전하고, 맑은 국악 가락 속에서 깊은 숲속 계곡 피서지를 찾아주는 낭만가입니다.`,
        themes: [`체험`, `먹거리`, `자연`, `음악`],
        hashtags: [`포도와인`, `국악체험`, `소백산계곡`],
        isMvpAvailable: !1,
        imageStyle: `from-purple-50 to-purple-100`,
        colorTheme: `purple`,
        characterImageStyle: `보라색 포도송이 모자가 통통하게 솟아오른 솜인형 요정`,
        characterToyDescription: `등 뒤에 장난감 아쟁/가야금을 메고 낭만적인 포도와인 터널을 짚어주는 인형`,
        characterTone: `풍류를 사랑하고 다정한 국악 낭만가`,
        regionVisualKeyword: `와인터널 시음관, 국악체험촌 한옥, 소백산 폭포 계곡, 가야금 선율`,
        regionIcon: `🍇`,
        regionHashtags: [`#포도와인`, `#국악체험`, `#소백산계곡`]
  }
];

export let buyeoDb = {
  gungnamji: {
    id: "gungnamji",
    name: "궁남지",
    category: "역사/자연 명소",
    themes: ["역사", "사진", "자연", "가족"],
    weatherFit: ["맑음", "흐림", "추움"],
    recommendedWeather: "맑은 날 저녁 또는 연꽃 시즌(7월)",
    rainFitScore: 4,
    stayMinutes: 90,
    walkingLoad: "보통",
    budgetLevel: "낮음",
    crowdLevel: "보통",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Korea-Buyeo-Gungnamji-01.jpg/800px-Korea-Buyeo-Gungnamji-01.jpg",
    gallery: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Korea-Buyeo-Gungnamji-01.jpg/800px-Korea-Buyeo-Gungnamji-01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Gungnamji_Lotus_Pond.jpg/800px-Gungnamji_Lotus_Pond.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Gungnamji_Poryongjeong.jpg/800px-Gungnamji_Poryongjeong.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Gungnamji_in_summer_01.jpg/800px-Gungnamji_in_summer_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Gungnamji_Night_View_01.jpg/800px-Gungnamji_Night_View_01.jpg"
    ],
    fallbackImage: "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=800&q=80",
    fallbackGallery: [
      "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1620121692029-d088224ddc74?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "우리나라 최초의 인공 정원이자, 백제 무왕의 서동요 전설이 깃든 로맨틱한 연못",
    longDescription: "궁남지는 단순한 연못이 아니라 백제 무왕과 신라 선화공주의 극적인 사랑 이야기를 품은 역사적 공간입니다. 신라 안압지의 모태가 되었을 정도로 뛰어난 백제의 정원 조경 기술을 보여주며, 못 중앙의 포룡정과 이를 잇는 목조 다리는 한 폭의 그림 같은 정취를 자아냅니다. 사계절 내내 다른 매력이 있지만, 여름철 흐드러지게 피어나는 천만 송이 연꽃과 밤바람에 흔들리는 버드나무 풍경은 부여 여행의 정수를 보여줍니다.",
    whyRecommended: "드넓은 연못과 정자가 어우러진 정적인 아름다움은 마음을 차분하게 가라앉힙니다. 특히 저녁 시간에 야간 조명이 켜지면 물 위에 비친 포룡정이 신비로운 분위기를 연출하여 인생 사진을 남기기에 최고의 장소입니다.",
    recommendedWith: ["정림사지", "국립부여박물관", "부여전통시장"],
    transportNotes: "부여시외버스터미널에서 도보로 약 15~20분 거리이며 경사가 없어 걷기 수월합니다. 시내버스는 배차 간격이 기므로 도보나 택시(기본요금 수준) 이용을 적극 추천합니다.",
    cautions: "그늘이 거의 없으므로 낮 시간대 방문 시 양산이나 모자를 필수로 지참해야 하며, 비가 오는 날에는 흙길이 다소 질척일 수 있습니다.",
    isIndoor: false,
    selectionWarnings: ["비 오는 날에는 야외 관람 시 우산이 필수이며 흙길 보행이 다소 제한될 수 있습니다.", "여름철 한낮(더운 날)에는 그늘막이 부족해 체력 소모가 큽니다. 모자나 생수를 지참하세요."],
    coords: [36.2662, 126.9125],
    busCoords: [36.2662, 126.9125],
    drtCoords: [36.2672, 126.9110],
    waitingPlace: "AT267 실내 대기실"
  },
  busosanseong: {
    id: "busosanseong",
    name: "부소산성 / 낙화암",
    category: "역사/자연 명소",
    themes: ["역사", "자연", "사진"],
    weatherFit: ["맑음", "흐림", "추움"],
    recommendedWeather: "맑은 날 오전",
    rainFitScore: 3,
    stayMinutes: 120,
    walkingLoad: "많음",
    budgetLevel: "보통",
    crowdLevel: "보통",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Korea-Buyeo-Busosanseong_Nakhwaam-01.jpg/800px-Korea-Buyeo-Busosanseong_Nakhwaam-01.jpg",
    gallery: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Korea-Buyeo-Busosanseong_Nakhwaam-01.jpg/800px-Korea-Buyeo-Busosanseong_Nakhwaam-01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Goran-sa_and_Baekma-gang_01.jpg/800px-Goran-sa_and_Baekma-gang_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Goransa_temple_hall_at_Buyeo.jpg/800px-Goransa_temple_hall_at_Buyeo.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Busosanseong_Forest_Trail.jpg/800px-Busosanseong_Forest_Trail.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Busosanseong_Sajaru_pavilion.jpg/800px-Busosanseong_Sajaru_pavilion.jpg"
    ],
    fallbackImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    fallbackGallery: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "백제의 마지막 요새이자 삼천궁녀의 슬픈 전설이 깃든 낙화암을 품은 울창한 숲길 산성",
    longDescription: "부소산성은 백제 사비 시대의 도성을 지키던 중심 산성입니다. 울창한 소나무 숲길을 따라 걷다 보면 백제 멸망의 슬픈 전설을 간직한 낙화암과 그 아래 백마강의 비경이 한눈에 들어오는 고란사에 닿을 수 있습니다. 산 전체가 야트막한 야산 형태여서 가벼운 산책으로 생각하기 쉽지만, 낙화암과 고란사까지 둘러보고 오려면 제법 가파른 숲길을 걸어야 합니다. 강바람과 숲 내음이 어우러져 사색하기에 제격인 코스입니다.",
    whyRecommended: "백마강을 내려다보는 낙화암에서의 조망은 가슴을 틔워주며, 고란사에서 맛보는 약수와 고란초의 신비로움이 여행의 재미를 더합니다. 역사적 비장미와 수려한 자연 경관을 동시에 느낄 수 있습니다.",
    recommendedWith: ["구드래나루터", "백마강 수상관광", "신동엽문학관"],
    transportNotes: "구드래나루터 방향에서 황포돛배(수상관광)를 타고 부소산성 후문(고란사 나루터)으로 진입한 뒤, 산성을 타고 내려와 정문으로 나가는 편도 코스를 짜면 도보 피로도를 크게 줄일 수 있습니다.",
    cautions: "흙길과 바위 계단이 많으므로 반드시 편안한 운동화를 착용해야 합니다. 야간에는 가로등이 없어 안전상의 이유로 입산이 통제됩니다.",
    isIndoor: false,
    selectionWarnings: ["비 오는 날이나 추운 날에는 산길 및 계단이 매우 미끄러워 낙상 위험이 높습니다.", "도보량이 많은 등산 수준의 코스이므로 무릎이 약하시거나 유모차/휠체어를 동반한 여행자는 정문 방면 완만한 구간만 추천합니다."],
    coords: [36.2895, 126.9121],
    busCoords: [36.2895, 126.9121],
    drtCoords: [36.2905, 126.9110],
    waitingPlace: "부소산성 고란사 정류장 쉼터"
  },
  jeonglimsaji: {
    id: "jeonglimsaji",
    name: "정림사지",
    category: "문화유산",
    themes: ["역사", "사진", "가족"],
    weatherFit: ["맑음", "흐림", "추움", "더움"],
    recommendedWeather: "늦은 오후 일몰 시간대",
    rainFitScore: 6,
    stayMinutes: 60,
    walkingLoad: "적음",
    budgetLevel: "보통",
    crowdLevel: "여유",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Five-story_Stone_Pagoda_at_Jeongnimsa_Temple_Site_in_Buyeo_201709.jpg/800px-Five-story_Stone_Pagoda_at_Jeongnimsa_Temple_Site_in_Buyeo_201709.jpg",
    gallery: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Five-story_Stone_Pagoda_at_Jeongnimsa_Temple_Site_in_Buyeo_201709.jpg/800px-Five-story_Stone_Pagoda_at_Jeongnimsa_Temple_Site_in_Buyeo_201709.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Korea-Buyeo-Jeongnimsaji-03.jpg/800px-Korea-Buyeo-Jeongnimsaji-03.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Korea-Buyeo-Jeongnimsaji-01.jpg/800px-Korea-Buyeo-Jeongnimsaji-01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Jeongnimsa_temple_site_museum.jpg/800px-Jeongnimsa_temple_site_museum.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Jeongnimsa_Five-story_Stone_Pagoda_Details.jpg/800px-Jeongnimsa_Five-story_Stone_Pagoda_Details.jpg"
    ],
    fallbackImage: "https://images.unsplash.com/photo-1542224566-6e85f2e6772f?auto=format&fit=crop&w=800&q=80",
    fallbackGallery: [
      "https://images.unsplash.com/photo-1542224566-6e85f2e6772f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1601999109332-542b18dbec57?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1547989453-11e67ffb3885?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "백제 조형미의 정점인 오층석탑이 우뚝 솟아 있는 사비 백제 불교 문화의 상징적 중심지",
    longDescription: "정림사지는 백제가 사비로 도읍을 옮긴 시기, 중심 성곽 내에 건립된 가장 중요한 사찰 터입니다. 이곳에 굳건히 서 있는 정림사지 오층석탑(국보)은 목조 탑의 부드러운 형식을 석조로 완벽히 재해석하여, 백제 특유의 절제되고 세련된 비례미를 뽐냅니다. 넓게 탁 트인 잔디 광장 한가운데 외로이 서 있는 석탑과 강당 안의 거대한 석조여래좌상은 세월의 무상함과 백제 예술의 영원함을 동시에 느끼게 합니다.",
    whyRecommended: "어스름한 일몰 무렵 석탑 너머로 노을이 깔리는 풍경은 압도적입니다. 불필요한 장식을 배제하고 선과 면만으로 구현한 절제미는 현대의 미니멀리즘과도 닮아 있어 깊은 울림을 줍니다.",
    recommendedWith: ["국립부여박물관", "궁남지", "부여전통시장"],
    transportNotes: "부여 중앙 통로에 위치해 있어 도보 접근성이 가장 훌륭한 곳입니다. 시내버스 정류장인 '정림사지' 또는 '부여군청'에서 내려 도보 3분 거리입니다.",
    cautions: "실외 넓은 터에 위치해 그늘이 부족하지만, 부지 내의 정림사지 박물관이 훌륭한 실내 대피처 역할을 해 주므로 날씨가 궂을 때는 박물관 관람을 병행하세요.",
    isIndoor: false,
    selectionWarnings: ["사찰 터 자체는 100% 야외이므로 눈/비가 오는 날씨에는 우산이 꼭 필요합니다. 다행히 내부에 있는 실내 박물관으로 신속히 이동이 가능합니다."],
    coords: [36.278385, 126.914107],
    busCoords: [36.278385, 126.914107],
    drtCoords: [36.2775, 126.9135],
    waitingPlace: "정림사지 안내센터 실내 로비"
  },
  buyeomuseum: {
    id: "buyeomuseum",
    name: "국립부여박물관",
    category: "박물관/실내",
    themes: ["역사", "실내", "가족", "사진"],
    weatherFit: ["맑음", "흐림", "비", "더움", "추움"],
    recommendedWeather: "비 오는 날 또는 한낮의 무더위 피하기",
    rainFitScore: 10,
    stayMinutes: 90,
    walkingLoad: "적음",
    budgetLevel: "낮음",
    crowdLevel: "보통",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Baekje_Geumdong_Daehyangro.jpg/800px-Baekje_Geumdong_Daehyangro.jpg",
    gallery: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Baekje_Geumdong_Daehyangro.jpg/800px-Baekje_Geumdong_Daehyangro.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Buyeo_National_Museum_Exhibit_01.jpg/800px-Buyeo_National_Museum_Exhibit_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Korea-Buyeo-Museum-01.jpg/800px-Korea-Buyeo-Museum-01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Baekje_gilt-bronze_crown_01.jpg/800px-Baekje_gilt-bronze_crown_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Buyeo_Museum_Central_Plaza_Media_Art.jpg/800px-Buyeo_Museum_Central_Plaza_Media_Art.jpg"
    ],
    fallbackImage: "https://images.unsplash.com/photo-1566121318599-db97b72e04f4?auto=format&fit=crop&w=800&q=80",
    fallbackGallery: [
      "https://images.unsplash.com/photo-1566121318599-db97b72e04f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "백제 문화의 위대한 걸작인 백제금동대향로를 직접 만나는 고품격 실내 역사 콘텐츠",
    longDescription: "국립부여박물관은 사비 백제 시대의 문화유산을 체계적으로 보존하고 전시하는 공간입니다. 이곳의 주인공은 단연 국보 '백제금동대향로'입니다. 향로에 조각된 오악사, 신선, 동물들의 섬세한 묘사를 관찰하다 보면 시간이 가는 줄 모릅니다. 중앙 로비 천장에서 상영되는 초대형 미디어아트 디지털 쇼는 백제의 백색 미학과 역동성을 시각적으로 극대화하여 현대적인 감동을 전달합니다.",
    whyRecommended: "비가 오거나 날씨가 극단적으로 덥고 추울 때 가장 쾌적하게 여행할 수 있는 대안입니다. 특히 백제금동대향로 단독 전시실은 조명과 연출이 매우 어둡고 조용하게 설정되어 향로의 금빛 광채에 오롯이 몰입할 수 있습니다.",
    recommendedWith: ["정림사지", "궁남지", "신동엽문학관"],
    transportNotes: "정림사지에서 남동쪽으로 도보 10분 거리에 있어 묶어 가기 좋습니다. 터미널에서도 택시로 기본요금 거리여서 뚜벅이 여행자의 허브 역할을 합니다.",
    cautions: "매주 월요일은 정기 휴관일이므로 방문 일정 수립 시 유의해야 합니다. 미디어아트 쇼는 상영 시간이 정해져 있으므로 입장 시 시간표를 먼저 확인하세요.",
    isIndoor: true,
    selectionWarnings: [],
    coords: [36.2751, 126.9197],
    busCoords: [36.2751, 126.9197],
    drtCoords: [36.2740, 126.9200],
    waitingPlace: "국립부여박물관 실내 북카페 쉼터"
  },
  baekjeculture: {
    id: "baekjeculture",
    name: "백제문화단지",
    category: "테마파크",
    themes: ["역사", "체험", "가족", "사진"],
    weatherFit: ["맑음", "흐림"],
    recommendedWeather: "맑은 날 오후 및 야간 개장 시기",
    rainFitScore: 4,
    stayMinutes: 180,
    walkingLoad: "많음",
    budgetLevel: "여유",
    crowdLevel: "보통",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Cheonjeongjeon_of_Sabi_Palace%2C_Baekje_Cultural_Land_01.jpg/800px-Cheonjeongjeon_of_Sabi_Palace%2C_Baekje_Cultural_Land_01.jpg",
    gallery: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Cheonjeongjeon_of_Sabi_Palace%2C_Baekje_Cultural_Land_01.jpg/800px-Cheonjeongjeon_of_Sabi_Palace%2C_Baekje_Cultural_Land_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Baekje_Cultural_Land_Pagoda_01.jpg/800px-Baekje_Cultural_Land_Pagoda_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Baekje_Cultural_Land_Sabi_Palace_Cheonjeongjeon.jpg/800px-Baekje_Cultural_Land_Sabi_Palace_Cheonjeongjeon.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Baekje_Cultural_Land_Living_Village.jpg/800px-Baekje_Cultural_Land_Living_Village.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Baekje_Cultural_Land_Wiryeseong.jpg/800px-Baekje_Cultural_Land_Wiryeseong.jpg"
    ],
    fallbackImage: "https://images.unsplash.com/photo-1608976478952-47ef0e8548bb?auto=format&fit=crop&w=800&q=80",
    fallbackGallery: [
      "https://images.unsplash.com/photo-1608976478952-47ef0e8548bb?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "백제 사비궁과 제향루, 생활문화마을까지 웅장하게 재현해 놓은 국내 최대 백제 역사 테마파크",
    longDescription: "백제문화단지는 찬란했던 백제 역사의 흔적을 완벽히 재현한 복합 문화 공간입니다. 거대한 사비궁 내부를 걷다 보면 왕실의 권위와 백제 단청의 단아하고 우아한 색감을 생생히 느낄 수 있습니다. 단지 뒷산의 제향루에 오르면 문화단지 전체 전경이 시원하게 펼쳐지며, 백제 한성시대의 위례성을 재현한 성곽과 전통가옥이 모여 있는 생활문화마을에서는 활쏘기 등 다양한 전통 놀이를 직접 체험해볼 수 있습니다.",
    whyRecommended: "사극 속에 들어온 듯한 웅장한 목조 아키텍처 배경으로 한복 체험 및 사진 촬영이 인기가 많습니다. 가을철 및 야간 개장 시 빛으로 채워지는 사비궁의 야경은 한옥의 미를 극대화해 보여줍니다.",
    recommendedWith: ["백마강 수상관광", "구드래나루터"],
    transportNotes: "부여 읍내에서 조금 떨어진 규암면에 위치해 있습니다. 시외버스터미널 건너편에서 400번대 버스를 타고 갈 수 있으나 배차가 적으므로 택시(약 8,000원~10,000원) 이용이나 시티투어버스 일정 조율을 추천합니다.",
    cautions: "부지가 매우 넓고 그늘이 부족해 걷는 피로도가 높습니다. 양산 대여 서비스를 활용하고 편안한 신발을 신는 것이 좋습니다.",
    isIndoor: false,
    selectionWarnings: ["부지가 매우 방대하고 완전히 개방된 야외 정원 위주이므로 비/눈이 오는 날 관람은 체력을 크게 고갈시킬 수 있습니다.", "읍내 외곽(규암면)에 위치하여 무차량 관광객은 일반 버스 배차 간격을 놓칠 경우 이동 수단 지연 주의가 가장 심한 명소입니다."],
    coords: [36.3015, 126.8978],
    busCoords: [36.3015, 126.8978],
    drtCoords: [36.3000, 126.8950],
    waitingPlace: "백제문화단지 안내소 대기실"
  },
  baekmagangwater: {
    id: "baekmagangwater",
    name: "백마강 수상관광 (황포돛배)",
    category: "이동/체험 명소",
    themes: ["자연", "체험", "가족", "사진"],
    weatherFit: ["맑음", "흐림", "더움"],
    recommendedWeather: "햇살이 밝은 날 오후",
    rainFitScore: 5,
    stayMinutes: 40,
    walkingLoad: "적음",
    budgetLevel: "보통",
    crowdLevel: "보통",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Baekma-gang_and_Goransa_01.jpg/800px-Baekma-gang_and_Goransa_01.jpg",
    gallery: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Baekma-gang_and_Goransa_01.jpg/800px-Baekma-gang_and_Goransa_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Nakhwaam_from_Baekmagang_River.jpg/800px-Nakhwaam_from_Baekmagang_River.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Goran-sa_and_Baekma-gang_01.jpg/800px-Goran-sa_and_Baekma-gang_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Baekmagang_Hwangpodotbae_Boat_01.jpg/800px-Baekmagang_Hwangpodotbae_Boat_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Baekmagang_Sunset_Bridge_01.jpg/800px-Baekmagang_Sunset_Bridge_01.jpg"
    ],
    fallbackImage: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=800&q=80",
    fallbackGallery: [
      "https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1505244208262-bd30d3a77825?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "황포돛배를 타고 선상에서 바라보는 낙화암과 부소산의 절경, 옛 백제의 뱃길을 복원한 수상 체험",
    longDescription: "백마강 수상관광은 구드래나루터에서 부소산성 뒤편 고란사나루터를 오가는 황포돛배 유람선입니다. 강물 위에서 스쳐 지어가는 낙화암 절벽의 붉은 글씨('낙화암')와 고란사 전경을 가장 가까이서 감상할 수 있는 독보적인 수단입니다. 탑승하는 동안 배 안에서 들려오는 가락과 구수한 해설은 여행의 흥을 돋우며, 강바람을 맞으며 돛을 매단 전통 배의 정취를 즐길 수 있습니다.",
    whyRecommended: "차 없는 여행자에게 단순한 즐길 거리를 넘어, 구드래(읍내 인근)와 부소산성 후문을 이어주는 훌륭한 지름길 역할을 해 줍니다. 강 위에서 보는 낙화암은 지상에서 보는 것과는 전혀 다른 웅장한 감동을 선사합니다.",
    recommendedWith: ["구드래나루터", "부소산성 / 낙화암"],
    transportNotes: "구드래나루터(부여읍 구드래조각공원 인근)와 고란사나루터(부소산성 내) 양쪽에서 왕복 및 편도 티켓을 끊을 수 있습니다. 무차량 여행자는 편도행으로 발권하여 산성 진입 경로로 쓰는 것이 효율적입니다.",
    cautions: "강한 바람이나 폭우, 강물 수위 변화 등 기상 악화 시 운항이 예고 없이 중단될 수 있으므로 날씨 정보를 미리 확인해야 합니다.",
    isIndoor: false,
    selectionWarnings: ["비가 많이 오거나 바람이 강한 날에는 운항이 즉각 결항되므로 대체 교통수단(도보/택시)을 강구해야 합니다."],
    coords: [36.2891, 126.9075],
    busCoords: [36.2891, 126.9075],
    drtCoords: [36.2875, 126.9015],
    waitingPlace: "구드래 선착장 쉼터"
  },
  gudraenaru: {
    id: "gudraenaru",
    name: "구드래나루터 / 구드래조각공원",
    category: "자연/로컬 명소",
    themes: ["자연", "사진", "가족", "먹거리"],
    weatherFit: ["맑음", "흐림", "추움"],
    recommendedWeather: "맑은 날 해질녘",
    rainFitScore: 5,
    stayMinutes: 50,
    walkingLoad: "보통",
    budgetLevel: "낮음",
    crowdLevel: "보통",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Gudrae_Naru_dock_at_Buyeo.jpg/800px-Gudrae_Naru_dock_at_Buyeo.jpg",
    gallery: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Gudrae_Naru_dock_at_Buyeo.jpg/800px-Gudrae_Naru_dock_at_Buyeo.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Nakhwaam_from_Baekmagang_River.jpg/800px-Nakhwaam_from_Baekmagang_River.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Baekma-gang_and_Goransa_01.jpg/800px-Baekma-gang_and_Goransa_01.jpg"
    ],
    fallbackImage: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=800&q=80",
    fallbackGallery: [
      "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "백마강변의 평화로운 잔디 광장과 예술 조각품들, 그리고 나루터 주변의 유명 맛집들이 모인 로컬 허브",
    longDescription: "구드래나루터는 백마강변에 조성된 드넓은 둔치 공원입니다. 과거 백제 사비 시대에 동아시아의 해상 교통 허브이자 무역항 역할을 했던 역사적 장소입니다. 지금은 아름다운 조각품들이 늘어선 예술 조각공원과 드넓은 억새밭길, 그리고 백마강 유람선(황포돛배)을 타는 포구로 탈바꿈했습니다. 공원 인근에는 부여의 대표 로컬 메뉴인 '쌈밥' 거리와 오래된 맛집들이 즐비하여 눈과 입이 동시에 즐거운 공간입니다.",
    whyRecommended: "유람선 탑승 전후로 시간이 뜰 때 탁 트인 강변 잔디밭을 산책하거나 벤치에 앉아 쉬기에 좋습니다. 해가 질 무렵 백마강으로 지는 일몰이 무척 아름답습니다.",
    recommendedWith: ["백마강 수상관광", "부소산성 / 낙화암", "부여전통시장"],
    transportNotes: "부여시외버스터미널에서 도보로 15분 정도로 인도가 잘 정비되어 있습니다. 구드래 쌈밥 골목에서 식사를 한 뒤 자연스럽게 산책하는 동선을 추천합니다.",
    cautions: "여름철 낮 시간대에는 햇볕을 피할 나무 그늘이 강변 쪽에 다소 부족하므로 선크림과 모자가 요긴하게 쓰입니다.",
    isIndoor: false,
    selectionWarnings: ["강변 둔치 특성상 비가 올 때 피할 건물 그늘막이 부족하며, 강풍 노출이 심합니다."],
    coords: [36.2861, 126.9033],
    busCoords: [36.2861, 126.9033],
    drtCoords: [36.2860, 126.9045],
    waitingPlace: "구드래조각공원 야외정자"
  },
  buyeotomb: {
    id: "buyeotomb",
    name: "부여왕릉원",
    category: "문화유산",
    themes: ["역사", "자연", "가족"],
    weatherFit: ["맑음", "흐림"],
    recommendedWeather: "맑고 선선한 바람이 부는 봄/가을",
    rainFitScore: 3,
    stayMinutes: 70,
    walkingLoad: "보통",
    budgetLevel: "보통",
    crowdLevel: "여유",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Korea-Buyeo-Neungsanri_Tombs-01.jpg/800px-Korea-Buyeo-Neungsanri_Tombs-01.jpg",
    gallery: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Korea-Buyeo-Neungsanri_Tombs-01.jpg/800px-Korea-Buyeo-Neungsanri_Tombs-01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Neungsan-ri_Tombs_01.jpg/800px-Neungsan-ri_Tombs_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Buyeo_Neungsan-ri_Royal_Tombs_Detail.jpg/800px-Buyeo_Neungsan-ri_Royal_Tombs_Detail.jpg"
    ],
    fallbackImage: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=800&q=80",
    fallbackGallery: [
      "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1492496913980-50134c7617a5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "부여의 나성 아래 아늑하게 자리 잡은 사비 백제 왕실의 고분군, 부드러운 능선이 그리는 쉼표",
    longDescription: "부여왕릉원(구 능산리고분군)은 사비 백제 시대의 왕과 왕족들의 무덤으로 추정되는 7기의 고분군입니다. 무덤 내부의 벽화와 출토된 화려한 유물들은 백제 후기 장묘 문화와 미술의 정수를 보여줍니다. 왕릉원 바로 옆에는 백제의 외곽 방어 성곽이었던 '나성'이 뻗어 있으며, 고분군의 나지막하고 둥근 능선들이 숲과 어우러져 한적하고 고즈넉한 사책의 산책길을 만들어 줍니다.",
    whyRecommended: "대단위 관광지보다 한적하고 방문객이 적어 고요하게 유적지를 전세 낸 듯한 힐링을 맛볼 수 있습니다. 능선들의 자연스러운 곡선미가 자아내는 평온함을 가만히 지켜보며 쉬어가기에 좋습니다.",
    recommendedWith: ["국립부여박물관", "정림사지"],
    transportNotes: "부여 읍내에서 동쪽으로 약 3km 떨어져 있어 도보 접근은 다소 무리입니다. 터미널 앞 정류장에서 버스(100, 300번대 등 동쪽 노선)로 약 10분 소요되나 배차가 드물어 버스 앱 확인 후 대기 시간이 길면 택시(약 5,000원) 이용을 추천합니다.",
    cautions: "실내 전시관(부여왕릉원 아트홀) 외에는 전 구역이 실외 잔디밭길이므로 우천 시 관람이 매우 제한됩니다.",
    isIndoor: false,
    selectionWarnings: ["비가 오는 날에는 실외 고분군 산책로의 매력이 쇠퇴하며 실외 배기 대기 여건이 불리합니다."],
    coords: [36.2783, 126.9405],
    busCoords: [36.2783, 126.9405],
    drtCoords: [36.2768, 126.9315],
    waitingPlace: "왕릉원 아트홀 실내 대기소"
  },
  buyeomarket: {
    id: "buyeomarket",
    name: "부여전통시장 및 로컬 먹거리 구역",
    category: "로컬/실내 명소",
    themes: ["먹거리", "실내", "체험"],
    weatherFit: ["맑음", "흐림", "비", "더움", "추움"],
    recommendedWeather: "식사 시간 또는 5일장이 서는 날(5, 10일)",
    rainFitScore: 8,
    stayMinutes: 60,
    walkingLoad: "적음",
    budgetLevel: "낮음",
    crowdLevel: "혼잡",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Korean_traditional_market_food_01.jpg/800px-Korean_traditional_market_food_01.jpg",
    gallery: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Korean_traditional_market_food_01.jpg/800px-Korean_traditional_market_food_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Buyeo_market_interior_02.jpg/800px-Buyeo_market_interior_02.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Korean_market_pancakes_jeon.jpg/800px-Korean_market_pancakes_jeon.jpg"
    ],
    fallbackImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    fallbackGallery: [
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "부여의 생생한 삶의 현장, 연잎밥·치킨 등 독특한 로컬 음식과 정겨운 시골 장터 풍경",
    longDescription: "부여전통시장은 백제의 도읍 부여의 맥을 잇는 활기 넘기는 생활 공간입니다. 상설로 운영되는 현대식 상가 건물과 함께 매 5일, 10일마다 열리는 5일장에는 부여 인근 농가에서 직접 가꾼 신선한 농산물과 풍성한 먹거리가 가득 펼쳐집니다. 부여의 대표 특산물인 '연잎'을 활용한 향긋한 연잎떡갈비정식이나, 시장 내의 명물 가마솥 옛날 통닭, 시골 칼국수 등 저렴하고 든든하게 한 끼를 해결할 수 있는 로컬 맛집들의 중심지입니다.",
    whyRecommended: "화려한 유적지 구경 뒤에 느끼는 소박하고 투박한 진짜 부여 사람들의 활력을 마주할 수 있습니다. 지붕이 아케이드식으로 가려져 있어 비가 오는 날에도 맛있는 로컬 음식 탐방을 쾌적하게 즐길 수 있습니다.",
    recommendedWith: ["정림사지", "국립부여박물관", "궁남지"],
    transportNotes: "부여시외버스터미널에서 북쪽으로 걸어서 5분 거리로, 뚜벅이 여행자가 부여에 도착하자마자 점심 식사를 해결하거나 여행을 마치고 돌아가기 전 들르기에 안성맞춤입니다.",
    cautions: "5일장 날이 아닐 때는 일반 평일 오후 늦게 문을 닫는 가게들이 있으므로 늦은 저녁 시간 방문보다는 아침이나 점심 식사를 목적으로 방문하는 것을 권장합니다.",
    isIndoor: true,
    selectionWarnings: [],
    coords: [36.2818, 126.9148],
    busCoords: [36.2818, 126.9148],
    drtCoords: [36.2810, 126.9095],
    waitingPlace: "중앙시장 팥죽 골목 쉼터"
  },
  muryangsa: {
    id: "muryangsa",
    name: "무량사",
    category: "역사/자연 명소",
    themes: ["역사", "자연", "사진"],
    weatherFit: ["맑음", "흐림", "비", "추움"],
    recommendedWeather: "맑고 고요한 산바람이 부는 오후",
    rainFitScore: 7,
    stayMinutes: 90,
    walkingLoad: "보통",
    budgetLevel: "보통",
    crowdLevel: "여유",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Muryangsa_temple_hall_in_Buyeo%2C_Korea.jpg/800px-Muryangsa_temple_hall_in_Buyeo%2C_Korea.jpg",
    gallery: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Muryangsa_temple_hall_in_Buyeo%2C_Korea.jpg/800px-Muryangsa_temple_hall_in_Buyeo%2C_Korea.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Buyeo_Muryangsa_Geungnakjeon.jpg/800px-Buyeo_Muryangsa_Geungnakjeon.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Muryangsa_stone_pagoda_at_Buyeo.jpg/800px-Muryangsa_stone_pagoda_at_Buyeo.jpg"
    ],
    fallbackImage: "https://images.unsplash.com/photo-1528164344705-47542687000d?auto=format&fit=crop&w=800&q=80",
    fallbackGallery: [
      "https://images.unsplash.com/photo-1528164344705-47542687000d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1504618223053-559bdef9dd5a?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "만수산 울창한 계곡 끝자락에 숨겨진 보물, 생육신 김시습이 마지막을 보낸 천년 고찰",
    longDescription: "무량사는 부여군 외곽 만수산 자락에 자리 잡은 유서 깊은 사찰입니다. '한량없는 보배가 가득한 절'이라는 이름처럼 임진왜란 때 소실되지 않고 살아남은 중층 구조의 극락전(보물)과 거대한 미륵불상 등 찬란한 문화재를 가득 품고 있습니다. 조선 세조 시기 생육신 중 한 명인 천재 시인 매월당 김시습이 세상을 등지고 입적한 곳으로도 유명합니다. 사찰로 향하는 만수산 숲길의 소나무 터널과 맑은 계곡 소리는 세속의 시름을 말끔히 씻어 줍니다.",
    whyRecommended: "외딴 깊은 산속에 위치해 있어 도시의 소음이 완벽히 차단됩니다. 특히 비가 가볍게 내리는 날 빗소리를 들으며 대웅전 처마 밑에 앉아 있는 고요한 템플 힐링 경험은 영혼을 위로해 줍니다.",
    recommendedWith: ["서동요테마파크"],
    transportNotes: "부여 읍내에서 서쪽으로 약 25km 떨어져 있어 가장 이동 난이도가 높은 명소입니다. 읍내 터미널에서 외산(무량사)행 시내버스(100번대 계열)를 타면 40분 정도 소요되며 하루 운행 횟수가 적으므로 돌아오는 버스 시간표를 탑승 시 필히 받아두거나 안내소에 문의해야 합니다.",
    cautions: "교통 접근성이 낮아 대중교통 배차를 놓치면 택시비 지출이 큽니다. 반드시 스마트폰 버스 정보 앱을 켜두거나 버스 터미널 시간표를 찍어 두세요.",
    isIndoor: false,
    selectionWarnings: ["부여 시내와 상당히 멀리 동떨어진 외진 사찰이므로 시내버스 배차 주기가 매우 깁니다. 뚜벅이 여행자는 차편 복귀 일정을 초단위로 확인하셔야 합니다."],
    coords: [36.3151, 126.7125],
    busCoords: [36.3151, 126.7125],
    drtCoords: [36.3150, 126.7175],
    waitingPlace: "무량사 입구 매표소 쉼터"
  },
  seodongyo: {
    id: "seodongyo",
    name: "서동요 테마파크",
    category: "테마파크",
    themes: ["체험", "사진", "가족"],
    weatherFit: ["맑음", "흐림"],
    recommendedWeather: "선선한 바람이 부는 맑은 날",
    rainFitScore: 3,
    stayMinutes: 100,
    walkingLoad: "보통",
    budgetLevel: "보통",
    crowdLevel: "여유",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Seodongyo_Theme_Park_drama_set_01.jpg/800px-Seodongyo_Theme_Park_drama_set_01.jpg",
    gallery: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Seodongyo_Theme_Park_drama_set_01.jpg/800px-Seodongyo_Theme_Park_drama_set_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Seodongyo_Theme_Park_Korean_houses.jpg/800px-Seodongyo_Theme_Park_Korean_houses.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Seodongyo_Theme_Park_Gate.jpg/800px-Seodongyo_Theme_Park_Gate.jpg"
    ],
    fallbackImage: "https://images.unsplash.com/photo-1498307818610-a4a920202150?auto=format&fit=crop&w=800&q=80",
    fallbackGallery: [
      "https://images.unsplash.com/photo-1498307818610-a4a920202150?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1473163928189-364b2c4e1135?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "아름다운 덕용저수지변에 펼쳐진 백제·신라시대식 오픈 세트장, 역사 속 주인공이 되는 이색 촬영지",
    longDescription: "서동요테마파크는 드라마 '서동요'를 비롯해 수많은 역사극의 촬영지로 세워진 거대한 야외 오픈 세트장입니다. 삼국시대 백제 왕궁과 귀족 가옥, 서민들의 초가집, 신라 왕궁까지 시대와 신분에 따른 가옥들이 정교하게 조각되어 있어 흥미를 자아냅니다. 세트장 바로 앞에는 잔잔하고 거대한 덕용저수지가 감싸 흐르고 있어 자연풍광이 뛰어나며, 저수지 둘레를 따라 조성된 수변 데크길 산책 코스도 훌륭합니다.",
    whyRecommended: "사람들이 북적이지 않는 넓고 조용한 공간에서 복식 체험이나 이색 역사 사진을 자유롭게 찍을 수 있습니다. 저수지 수변 길의 데크 로드가 길게 뻗어 있어 아름다운 인생 샷을 건질 수 있습니다.",
    recommendedWith: ["무량사"],
    transportNotes: "부여 남서부 충화면에 위치해 대중교통 이용이 힘든 축에 속합니다. 읍내 터미널에서 충화행 시내버스를 타야 하나 운행 횟수가 매우 드무니 출발 전 시간을 세밀히 대조하거나 관광택시/카셰어링 연동 계획을 사전에 세워두어야 합니다.",
    cautions: "야외 매점이 운영되지 않는 비수기에는 마실 음료를 챙겨가는 것이 좋습니다. 우천 시에는 세트장 내부 보행로가 미끄러울 수 있어 주의해야 합니다.",
    isIndoor: false,
    selectionWarnings: ["시외 지역이며 그늘막이 부족하며, 강풍 노출이 심합니다."],
    coords: [36.1963, 126.8152],
    busCoords: [36.1963, 126.8152],
    drtCoords: [36.2080, 126.8140],
    waitingPlace: "서동요테마파크 안내센터"
  },
  shindongyeop: {
    id: "shindongyeop",
    name: "신동엽문학관",
    category: "박물관/실내",
    themes: ["역사", "실내", "가족", "사진"],
    weatherFit: ["맑음", "흐림", "비", "더움", "추움"],
    recommendedWeather: "비 오는 날 또는 한낮의 무더위 피하기",
    rainFitScore: 10,
    stayMinutes: 90,
    walkingLoad: "적음",
    budgetLevel: "낮음",
    crowdLevel: "보통",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Sin_Dong-yeop_House_at_Buyeo.jpg/800px-Sin_Dong-yeop_House_at_Buyeo.jpg",
    gallery: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Sin_Dong-yeop_House_at_Buyeo.jpg/800px-Sin_Dong-yeop_House_at_Buyeo.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Shin_Dong-yeop_Poetry_Monument_01.jpg/800px-Shin_Dong-yeop_Poetry_Monument_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Korea-Buyeo-Museum-01.jpg/800px-Korea-Buyeo-Museum-01.jpg"
    ],
    fallbackImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=800&q=80",
    fallbackGallery: [
      "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80"
    ],
    shortDescription: "민족시인 신동엽의 생가와 문학 세계를 기리는 모던하고 감각적인 건축 예술 공간",
    longDescription: "신동엽문학관은 대한민국 현대 민족문학의 거장 신동엽 시인(\"껍데기는 가라\", \"금강\")의 고향 부여에 세워진 문학 예술 공간입니다. 세계적인 건축가 승효상 선생이 설계한 문학관 건물 자체가 하나의 예술작품으로, 주변 시골 골목 풍경 속에 겸손하고 나지막하게 어우러져 있습니다. 시인의 육필 원고와 유품들을 감상하고 옥상 정원에 오르면 주변 시골 마을 풍경과 부여의 하늘이 한눈에 포개어지며 깊은 사색을 선물합니다.",
    whyRecommended: "화려한 백제 왕실 유적지와 달리, 부여의 골목 깊숙이 자리 잡은 현대 한국 문학의 지적인 온기를 느낄 수 있습니다. 문학관 내부 쉼터와 옥상의 잔디 언덕은 도보 여행자에게 가장 조용하고 세련된 치유의 쉼터를 제공합니다.",
    recommendedWith: ["부소산성 / 낙화암", "부여전통시장", "정림사지"],
    transportNotes: "부여시외버스터미널에서 도보로 7~10분 거리이며 부소산성 정문에서도 가까워 도보 여행 중 한 박자 쉬어가기 딱 좋은 최고의 위치를 자랑합니다.",
    cautions: "매주 월요일은 정기 휴관일이므로 방문 일정 수립 시 유의해야 합니다.",
    isIndoor: true,
    selectionWarnings: [],
    coords: [36.2768, 126.9121],
    busCoords: [36.2768, 126.9121],
    drtCoords: [36.2775, 126.9085],
    waitingPlace: "문학관 북카페 안심 대기실"
  }
};

export const TRANSPORTS: Transport[] = [
  {
    id: "walk",
    name: "도보",
    type: "general",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    suitableFor: "체력이 양호한 1~2인, 부여 읍내 핵심 유적지 중심 여행자",
    minPeople: 1,
    maxPeople: 4,
    reservationRequired: false,
    costLevel: "낮음",
    reliability: "최상 (교통 체증 무관)",
    weatherSensitive: false,
    walkingBurden: "많음",
    description: "가장 느리지만 유적지와 골목 구석구석 숨겨진 부여의 디테일을 눈에 담을 수 있는 자연주의 이동 방식입니다.",
    strength: "비용이 전혀 들지 않고 차편을 기다리는 시간 낭비가 없으며, 정림사지-박물관-궁남지로 이어지는 핵심 플랫 코스에 최적화되어 있습니다.",
    caution: "인도가 다소 좁은 구간이 있을 수 있고 한여름 햇볕 아래 장시간 보행 시 체력 소모가 매우 큽니다. 물과 모자가 필수입니다.",
    whyUseThis: "부여 읍내 주요 코스는 도보 10~15분 안팎으로 촘촘히 엮여 있어 대기 시간이 긴 시내버스보다 훨씬 신속하게 도달할 수 있기 때문입니다.",
    selectionWarnings: ["비가 많이 오거나 폭염/한파 조건에서는 도보 보행 시 체력 소모가 극심하고 옷/신발이 젖어 여행 피로도가 급증합니다."]
  },
  {
    id: "bus",
    name: "일반 시내버스",
    type: "localTransit",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    suitableFor: "시간 여유가 있는 1인 뚜벅이, 예산을 아끼고 싶은 고독한 방랑자",
    minPeople: 1,
    maxPeople: 20,
    reservationRequired: false,
    costLevel: "낮음",
    reliability: "낮음 (배차 간격이 30분~2시간으로 매우 김)",
    weatherSensitive: false,
    walkingBurden: "보통",
    description: "부여 군민들의 진짜 발이 되어 주는 대중교통으로, 외곽 명소인 백제문화단지나 무량사로 갈 때 요긴합니다.",
    strength: "요금이 저렴하고 차창 밖으로 보이는 부여의 아늑한 전원 풍경과 순박한 시골 인심을 날것 그대로 느낄 수 있습니다.",
    caution: "배차 간격이 매우 길고 불규칙하므로, 버스 정보 단말기가 없는 정류장에서는 스마트폰 실시간 버스 정보 확인이 필수입니다.",
    whyUseThis: "외곽의 먼 유적지(무량사, 서동요테마파크)로 이동할 때 비용 지출을 최소화하기 위한 불가피한 대안 수단입니다.",
    selectionWarnings: ["배차 간격이 극단적으로 기므로 계획 없이 탑승하려 할 경우 길바닥에서 1시간 이상 낭비할 수 있습니다."]
  },
  {
    id: "taxi",
    name: "일반 택시",
    type: "taxi",
    image: "https://images.unsplash.com/photo-1494783367193-149034c05e8f?auto=format&fit=crop&w=800&q=80",
    suitableFor: "2~4인 동반 여행자, 시간 절약과 편안함을 선호하는 쾌적파 여행자",
    minPeople: 1,
    maxPeople: 4,
    reservationRequired: false,
    costLevel: "보통",
    reliability: "높음 (읍내에서는 즉시 호출 가능, 카카오택시 가동)",
    weatherSensitive: false,
    walkingBurden: "적음",
    description: "부여 읍내 어디서든 신속하게 잡히며, 짧은 일정 속에서 길바닥에서 낭비하는 대기 시간을 제로로 만들어주는 합리적 대안입니다.",
    strength: "대기 시간이 전혀 없고 에어컨/히터 바람 속에서 목적지 정문 앞까지 문전 연결성(Door to Door)을 완벽히 실현해 줍니다.",
    caution: "무량사나 서동요테마파크 같은 극단적인 시외곽 왕복 시 편도 2~3만 원 이상의 비교적 높은 지출이 발생할 수 있습니다.",
    whyUseThis: "부여 읍내 대부분의 거리가 기본 요금 또는 5천 원 내외로 정산되어, 2인 이상 탑승 시 시간 절약과 편의 대비 가성비가 훌륭하기 때문입니다.",
    selectionWarnings: ["1인 여행 시 장거리 외곽 구간(무량사 등) 이용은 누적 택시 요금 부담이 너무 커집니다."]
  },
  {
    id: "citytour",
    name: "부여 시티투어버스",
    type: "fixedCourse",
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
    suitableFor: "첫 부여 방문객, 계획 세우기 귀찮은 단체/가족 여행자",
    minPeople: 1,
    maxPeople: 40,
    reservationRequired: true,
    costLevel: "보통",
    reliability: "최상 (정해진 일정 및 시간 준수)",
    weatherSensitive: false,
    walkingBurden: "보통",
    description: "주요 문화유산 테마를 중심으로 문화관광해설사와 함께 전용 버스를 타고 하루 동안 편안하게 유적지를 도는 기획형 투어 방식입니다.",
    strength: "버스를 타고만 있으면 알아서 문 앞까지 데려다주고 전문 해설사의 재미있는 백제 야사가 결합되어 알찬 학습이 가능합니다.",
    caution: "사전 예약이 필요하며 지정된 출발 일시와 코스 일정표에 내 개인 스케줄을 완전히 맞춰 움직여야 하는 속박감이 있습니다.",
    whyUseThis: "교통편을 일일이 검색하는 스트레스 없이 단 하루 만에 부여의 주요 하이라이트 핵심 명소들을 편하게 쓸어 담고 싶을 때 매우 유용한 대안입니다.",
    selectionWarnings: ["시티투어는 개별 자율 관광 노선이 아니므로, 정해진 배차/코스를 이탈하여 마음대로 다른 명소로 갈 수 없습니다."]
  },
  {
    id: "ferry",
    name: "백마강 황포돛배",
    type: "tourTransport",
    image: "https://images.unsplash.com/photo-1505244208262-bd30d3a77825?auto=format&fit=crop&w=800&q=80",
    suitableFor: "자연 감상을 좋아하는 가족 및 연인 여행자",
    minPeople: 1,
    maxPeople: 30,
    reservationRequired: false,
    costLevel: "보통",
    reliability: "보통 (날씨 및 강물 유속 영향)",
    weatherSensitive: true,
    walkingBurden: "적음",
    description: "부소산성 고란사나루터와 구드래나루터 사이 백마강 물길을 유영하며 강 위에서 절경을 유람하는 뱃길 이동 수단입니다.",
    strength: "배를 타고 흐르는 백마강 바람을 맞으며 강변에 우뚝 솟은 낙화암을 가장 장엄하게 올려다보는 독보적인 뷰 포인트를 제공합니다.",
    caution: "단순한 대중교통이 아닌 유료 유람선 요금이 발생하며 기상 악화(폭우, 강풍) 시에는 전면 운항이 중단됩니다.",
    whyUseThis: "도보로 부소산성을 오르는 육로 코스보다 뱃길을 결합하면 훨씬 덜 힘들고 백마강 자체의 레저 체험을 가미할 수 있어 이동과 재미가 동시 해결됩니다.",
    selectionWarnings: ["비바람에 취약하여 눈/비 오거나 안개가 심한 날은 운항 자체가 취소되므로 일정 백업 대안이 필요합니다."]
  },
  {
    id: "amphibious",
    name: "수륙양용버스",
    type: "tourTransport",
    image: "https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=800&q=80",
    suitableFor: "색다른 모험을 원하는 커플, 아이가 있는 가족 단위 관광객",
    minPeople: 1,
    maxPeople: 40,
    reservationRequired: true,
    costLevel: "높음",
    reliability: "높음 (예약제 운영)",
    weatherSensitive: true,
    walkingBurden: "적음",
    description: "도로 위를 달리던 버스가 백마강 물속으로 그대로 첨벙 빠져들어 배로 변신하는 국내 최초의 모험 체험형 관광 교통입니다.",
    strength: "물에 들어가는 순간의 짜릿한 스릴과 육상 및 수상 관광을 한 번에 경험할 수 있는 강렬한 엔터테인먼트 요소가 강합니다.",
    caution: "이용 요금이 비교적 고가이며 인기 요일에는 조기 매진되므로 일찍 인터넷 예매를 서둘러야 합니다.",
    whyUseThis: "백제문화단지와 백마강 주변을 단순한 이동이 아닌 평생 기억에 남을 이색적인 어트랙션 코스로서 즐기고 싶을 때 선택합니다.",
    selectionWarnings: ["요금이 상당히 고가(인당 약 2~3만원선)로 가성비 위주의 알뜰 배낭여행자에게는 지출 경고 대상입니다."]
  },
  {
    id: "tourism_taxi",
    name: "부여 관광택시",
    type: "reservation",
    image: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=800&q=80",
    suitableFor: "외곽의 무량사·서동요테마파크까지 자유롭게 일정을 누비고픈 뚜벅이 그룹",
    minPeople: 2,
    maxPeople: 4,
    reservationRequired: true,
    costLevel: "높음",
    reliability: "최상 (개인 맞춤 전용 기사 배정)",
    weatherSensitive: false,
    walkingBurden: "적음",
    description: "원하는 시간 and 노선에 맞춰 기사가 직접 대기하고 데려다주는 맞춤형 관광 전세 택시 모델입니다.",
    strength: "내가 정한 일정 루트대로 외곽지까지 안심하고 다닐 수 있어 일반 버스의 긴 배차 시간 공포를 완벽히 해결해 줍니다.",
    caution: "가격대가 단독 사용 시 다소 높으나, 3~4인 동승 시 가성비가 상승합니다.",
    whyUseThis: "대중교통 주기가 너무 뜸한 산사(무량사)나 테마파크 등을 스트레스 없이 연속 이동하여 하루 만에 격파하기 좋습니다.",
    selectionWarnings: ["1인 홀로 여행 시 비용 분담이 불가하므로 경제성이 매우 나쁩니다."]
  },
  {
    id: "drt",
    name: "수요응답형 버스 (DRT)",
    type: "public",
    image: "https://images.unsplash.com/photo-1557223562-6c77ef16210f?auto=format&fit=crop&w=800&q=80",
    suitableFor: "대기시간 절약을 선호하는 합리적 스마트 뚜벅이",
    minPeople: 1,
    maxPeople: 10,
    reservationRequired: true,
    costLevel: "낮음",
    reliability: "매우 신속 (앱 호출 및 노선 자동 배차)",
    weatherSensitive: false,
    walkingBurden: "적음",
    description: "고정 노선 없이 실시간 호출 수요에 매칭해 정류장 간 최단 경로를 가동하는 차세대 콜버스 모델입니다. 부여 노선을 전담하여 시외버스터미널부터 궁남지, 정림사지, 백제문화단지, 공주역 KTX를 빠르게 연계합니다.",
    strength: "일반 버스에 준하는 저렴한 요금으로 택시 수준의 개인 맞춤형 신속 노선을 실현합니다.",
    caution: "부여-공주역 노선을 연계하여 탑승 가능하며, 승하차 지점 및 도보 동선을 획기적으로 줄여줍니다.",
    whyUseThis: "대중교통 주기가 너무 뜸한 읍내 주요 환승 노선에서 대기 시간 없이 원스톱 호출로 버스를 타기 위함입니다.",
    selectionWarnings: ["부여 스마트 관광 가이드의 특별 노선으로, 선택하신 관광명소 순서대로 안전하게 이동이 가능합니다."]
  }
];

export const WAITING_SPOTS: WaitingSpot[] = [
  {
    id: "ws_gungnamji_cafe",
    name: "궁남지 향기 가득 카페",
    type: "카페",
    goodForRain: true,
    goodForNight: true,
    recommendedWaitMinutes: 30,
    description: "궁남지 정문 건너편에 바로 위치하여 비를 피하거나 여름 햇볕을 피하며 창밖으로 연못 뷰를 관찰할 수 있는 아늑한 카페입니다.",
    nearPlaceId: "gungnamji"
  },
  {
    id: "ws_buso_shelter",
    name: "부소산성 고란사 정류장 쉼터",
    type: "정류장 주변",
    goodForRain: false,
    goodForNight: false,
    recommendedWaitMinutes: 15,
    description: "황포돛배 탑승이나 버스를 기다릴 때 가볍게 앉아 강바람을 맞을 수 있는 야외 정자 및 지붕 쉼터입니다.",
    nearPlaceId: "busosanseong"
  },
  {
    id: "ws_museum_lobby",
    name: "국립부여박물관 실내 북카페 쉼터",
    type: "쉼터/실내",
    goodForRain: true,
    goodForNight: false,
    recommendedWaitMinutes: 40,
    description: "박물관 전시동 내에 조용하게 책을 읽고 무료로 고속 Wi-Fi와 스마트폰 충전을 하며 실내 대기를 할 수 있는 최고의 프리미엄 대기소입니다.",
    nearPlaceId: "buyeomuseum"
  },
  {
    id: "ws_market_shikdang",
    name: "중앙시장 팥죽 골목 쉼터",
    type: "식당",
    goodForRain: true,
    goodForNight: true,
    recommendedWaitMinutes: 20,
    description: "정겨운 팥죽집과 전통 찻집들이 옹기종기 모여 있는 가려진 전통시장 아케이드 통로로, 추위나 눈비를 피하며 요기하기 좋습니다.",
    nearPlaceId: "buyeomarket"
  },
  {
    id: "ws_jeongrim_museum",
    name: "정림사지 박물관 로비 실내 대기소",
    type: "쉼터/실내",
    goodForRain: true,
    goodForNight: false,
    recommendedWaitMinutes: 30,
    description: "정림사지 야외 사찰 터 한켠에 마련된 박물관 실내 로비로, 시원한 냉난방 에어컨과 넓은 쇼파 좌석이 있어 한낮 더위를 피하기 훌륭합니다.",
    nearPlaceId: "jeongrimsaji"
  }
];
